# Generated by Django 5.0.3 on 2024-03-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('km', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_plate', models.CharField(max_length=7)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido')], default='ativo', max_length=7)),
            ],
        ),
    ]
