# Generated by Django 5.0.3 on 2024-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_image_alter_car_status_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
