# Generated by Django 5.0.3 on 2024-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_vendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vendido',
        ),
        migrations.AddField(
            model_name='vendidos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='vendidos/'),
        ),
        migrations.AlterField(
            model_name='vendidos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
