# Generated by Django 5.0.3 on 2024-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_car_vendido_vendidos_imagem_alter_vendidos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendidos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
